### ISSUE TITLE
[BUG] Dark Brotherhood Sanctuary CTD

### ISSUE THREAD

**Issue by KhaosEU** [The-Animonculory/AVO-NG#2]
**Upload your crash log** - [crash-2023-04-10-04-54-06.log](https://github.com/The-Animonculory/AVO-NG/files/11187747/crash-2023-04-10-04-54-06.log)

**Required: Modlist.txt** - [modlist.txt](https://github.com/The-Animonculory/AVO-NG/files/11187757/modlist.txt)

**Describe the bug**
Game crashes to desktop upon entering the Dark Brotherhood Sanctuary near Falkreath. I believe I've narrowed it down to a specific issue with the 'AVONG Bodyslide - robedarkbrotherhood' file. When removed I don't get the crash.

**To Reproduce**
Steps to reproduce the behaviour:

1. Get to Dark Brotherhood Sanctuary.
2. Select the answer to enter the Sanctuary.

**Modlist version** - 4.0

**Did you add any additional mods?** - No

**Comment by Althro** [comment]
Thanks for the report, I'll look into getting this fixed :)

**Comment by Althro** [comment]
Fixed in 4.0.1
