### ISSUE TITLE
Unable to download Upscaler Bases.zip

### ISSUE THREAD

**Issue by HizorGungine** [The-Animonculory/AVO-NG#3]
I've checked the authored files from Wabbajack, the manifest for the mod for checking file sizes, and the Skyrim Upscaler mod files and I cannot find any file named "Upscaler Bases.zip" that this is looking for. 
My only assumption is that it was removed?

Either way this one file is preventing the the installation from being completed for me.
[Wabbajack.current.log](https://github.com/The-Animonculory/AVO-NG/files/11371227/Wabbajack.current.log)

**Comment by Althro** [comment]
The file was removed due to a copyright claim. You will need to wait until 4.2 is released to install the list.
